url: https://blogi.hinaaja.org
title: "M/S Vega"
author: "Lari Mahlio"
description: "Teräshinaajan kunnostusta."
locale: fi-FI
header_type: image
header_img: /assets/img/vega_vanha.jpeg

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
#email: "lari@hinaaja.org"
#twitter_username: "pulkkla"
github_username: "plektra"
#blinkedin_username: "lari.mahlio"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "chulapa-jekyll"
github: [metadata]
repository: dieghernan/chulapa-jekyll-101

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: default
      tags: Other
      header_type: post
      header_img: /assets/img/vega_vanha.jpeg
      show_breadcrumb: true
      breadcrumb_list:
        - label: Etusivu
          url: /
        - label: Blogi
          url: /blog
      show_comments: true

chulapa-skin:
  skin: graymor

footer:
  copyright: "&copy; 2024 Lari Mahlio"

navbar:
  style: dual
  nav:
  - title: Etusivu
    url: /
  - title: Perustiedot
    url: /perustiedot
  - title: Blogi
    url: /blog/
  
paginate_path: "/blog/page:num/"
paginate: 10

comments:
  provider: cusdis
  cusdis_app_id: "4f5fc1de-9ebd-47bf-a6d9-1fea07785471"